# Generated by Django 4.1.5 on 2023-01-27 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower_set',
            field=models.ManyToManyField(blank=True, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, help_text='48px * 48px 이하의 jpg/png 이미지를 업로드해주세요', upload_to='accounts/profile/%Y/%m/%d'),
        ),
    ]
